config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      root 'welcome#index'
      get 'doc' => 'welcome#doc'
      get ':apikey/get/ssids' => 'ssids#get'
      get ':apikey/get/locations' => 'locations#get', :as => 'get_locations'
      get ':apikey/set/location/:address/:identifier/:city/:ap' => 'entries#set', :as => 'set_location'
      get ':apikey/set/location/:address/:identifier/:city/:ap/:ssid' => 'entries#set', :as => 'set_location_with_ssid'
      get ':apikey/get/policies' => 'orgpolicies#get'
      match ':apikey/set/policy/lang/:lang/*url' => 'orgpolicies#set', :via => :get, :format => false, constraints: { url: /\D*/ }
      get ':apikey/get/infos' => 'orginfos#get'
      match ':apikey/set/info/lang/:lang/*url' => 'orginfos#set', :via => :get, :format => false, constraints: { url: /\D*/ }
      get ':apikey/get/loc_names' => 'loc_names#get'
      match ':apikey/set/loc_name/:location_id/lang/:lang/*name' => 'loc_names#set', :via => :get, :format => false, constraints: { url: /\D*/ }
      match ':apikey/set/ssid/:id/:key/:value' => 'ssids#set', :via => :get,  :format => false, constraints: { url: /\D*/ }
      match ':apikey/set/ssid/:key/:value' => 'ssids#set', :via => :get,  :format => false, constraints: { url: /[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}/}

    end
  end

  root 'welcome#index'
  get 'apidoc' => 'welcome#apidoc'
  get 'exporter/institutions'
  get 'import' => 'institutions#new_import'
  post '/institution/import' => 'institutions#import'
  resources :institutions

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :orgnames
  has_many :orginfos, autosave: true
  has_many :orgpolicies, autosave: true
  has_many :orgssids, autosave: true
  has_many :entries, autosave: true
  has_many :locations, autosave: true
  accepts_nested_attributes_for :orgnames
  accepts_nested_attributes_for :orginfos
  accepts_nested_attributes_for :orgpolicies
  accepts_nested_attributes_for :orgssids
  accepts_nested_attributes_for :locations
  accepts_nested_attributes_for :entries
  # minimum length of a realm would be four letters: "a.fi". this spot could house some custom validation which checks if
  # realm exists by telneting to target radius port (or something)...
  validates :inst_realm, presence: true, length: {minimum: 4}, uniqueness: {scope: [:inst_realm], message: "Given realm already exists!"}
  validates :institution_type, presence: true, :inclusion => {:in => [2,3]}  # institution type can be either 2 or 3. type 1 is the NRO
  validates_uniqueness_of :inst_realm, :scope => [:country, :institution_type, :inst_realm ], message: "Institution already exists"

  before_create :new_apikey, :default_country
  after_create :create_default_ssid

  def generate_api_key
    loop do
      token = SecureRandom.base64.tr('+/=', 'Qrt')
      break token unless Institution.exists?(apikey: token)
    end
  end

  def primary_name
    orgnames.first.name
#    self.orgnames.first.name
  end

  def primary_info_url
    self.orginfos.first.url
  end

  def primary_policy_url
    self.orgpolicies.first.url
  end

  def create_default_ssid
     Orgssid.create_default(self.id)
  end

  private
  def new_apikey
    self.apikey = generate_api_key()

  end

  def default_country
    raise "NRO_COUNTRY env variable not defined!" if ENV['NRO_COUNTRY'].nil?
    raise "NRO_COUNTRY env variable is invalid!" if ISO3166::Country.find_all_by_alpha2(ENV['NRO_COUNTRY']).nil?
    self.country = ENV['NRO_COUNTRY']
  end

end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  include InstitutionsHelper
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    @locations = Location.where(institution_id: params[:id])
 #   @latest_entries = Entry.where(institution_id: params[:id]).order(:location_id => :desc).group(:location_id)
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
    @countries = ISO3166::Country.codes
    @default_langs = ENV['EDUROAM_API_DEFAULT_LANGS'].split(',') 
    @institution.orgnames.build
    @institution.orgnames.last.lang = 'en'
    @institution.orgpolicies.build
    @institution.orgpolicies.last.lang = 'en'
    @institution.orginfos.build
    @institution.orginfos.last.lang = 'en'
    i = 0
    (@default_langs.count).times do
      @institution.orgnames.build
      @institution.orgnames.last.lang = @default_langs[i]
      @institution.orgpolicies.build
      @institution.orgpolicies.last.lang = @default_langs[i]
      @institution.orginfos.build
      @institution.orginfos.last.lang = @default_langs[i]
      i += 1
    end
    @institution_types = {'IdP&SP' => 3, 'SP' => 2}
  end

  # GET /institutions/1/edit
  def edit
    @institution = Institution.find(params[:id])
    @countries = ISO3166::Country.codes
    @institution_types = {'IdP&SP' => 3, 'SP' => 2}
  end

  # POST /institutions
  # POST /institutions.json

  def create
    @institution = Institution.new(institution_params)
    puts institution_params

    respond_to do |format|
      if @institution.save
        format.html {redirect_to @institution, notice: 'Institution was successfully created.'}
        format.json {render :show, status: :created, location: @institution}
      else
        format.html {render :new}
        format.json {render json: @institution.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html {redirect_to @institution, notice: 'Institution was successfully updated.'}
        format.json {render :show, status: :ok, location: @institution}
      else
        format.html {render :edit}
        format.json {render json: @institution.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html {redirect_to institutions_url, notice: 'Institution was successfully destroyed.'}
      format.json {head :no_content}
    end
  end


  def new_import

  end

  def import


    file_data = params[:file]

    if file_data.respond_to?(:read)
      xml_contents = file_data.read
      import_data xml_contents

      flash[:success] = "<strong>File Imported!</strong>"
      redirect_to institutions_url

    elsif file_data.respond_to?(:path)
      xml_contents = File.read(file_data.path)
      import_data xml_contents
      flash[:success] = "<strong>File Imported!</strong>"
      redirect_to institutions_url
    else
      logger.error "Bad file_data: #{file_data.class.name}: #{file_data.inspect}"
      flash[:error] = "There was a problem importing the file.<br>
      <strong>#{exception.message}</strong><br>"
      redirect_to import

    end


  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_institution
    @institution = Institution.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def institution_params
    params.require(:institution).permit(:country,
                                        :institution_type,
                                        :inst_realm,
                                        :address,
                                        :city,
                                        :contact_name,
                                        :contact_email,
                                        :contact_phone,
                                        orgnames_attributes: [:id, :lang, :name],
                                        orgpolicies_attributes: [:id, :lang, :url],
                                        orginfos_attributes: [:id, :lang, :url],
                                        orgssids_attributes: [:id, :number, :wpa_tkip, :wpa_aes, :wpa2_tkip, :wpa2_aes, :port_restrict, :transp_proxy, :ipv6, :nat])

  end
end

app/helpers/api/v1/institutions_helper.rb
module Api::V1::InstitutionsHelper
  include Api::V1::BaseHelper
end

app/helpers/institutions_helper.rb
require 'csv'
module InstitutionsHelper

  def value_bool(input)
    if input == "true"
      return true
    else
      return false
    end
  end



  def import_data import_file
#    import_file = File.read("../institution.xml")

    doc = Nokogiri::XML(import_file) do |config|
      config.options = Nokogiri::XML::ParseOptions::STRICT | Nokogiri::XML::ParseOptions::NOBLANKS
    end
    xsd = Nokogiri::XML::Schema(File.read("lib/assets/institution.xsd"))
    if xsd.valid?(doc)
      q = Queue.new
      o = OpenStruct.new(Hash.from_xml(import_file))

      # OpenStruct doesn't map attributes, so given that the lang-attributes
      # are found in the document in same order, they can be queued and then dequeued appropriately
      doc.search("[lang]").each do |s|
        q.push(s['lang'])
      end
      Array.wrap(o['institutions']['institution']).each do |x|
        pp x.inspect
        n = Institution.new
        n.country = x['country']

        if Array(x['inst_realm']).count > 1
          csv_string = CSV.generate do |csv|
            csv << x['inst_realm']

          end
        else
          csv_string = x['inst_realm']
        end

        n.inst_realm = csv_string


        tmp_p = ""
        tmp_n = ""
        tmp_e = ""

        if Array.wrap(x['contact']).count > 1
          x['contact'].each do |xc|
            tmp_n += "#{xc['name']}, "
            tmp_p += "#{xc['phone']}, "
            tmp_e += "#{xc['email']}, "
          end
          n.contact_name = tmp_n.chomp(", ")
          n.contact_email = tmp_e.chomp(", ")
          n.contact_phone = tmp_p.chomp(", ")

        else
          n.contact_name = x['contact']['name']
          n.contact_email = x['contact']['email']
          n.contact_phone = x['contact']['phone']

        end


        n.institution_type = x['type'].to_i
        n.address = x['address']['street']
        n.city = x['address']['city']
        Array.wrap(x['org_name']).each do |org|
          n.orgnames.build
          n.orgnames.last.name = org || " "
          n.orgnames.last.lang = q.pop
        end

        Array.wrap(x['policy_URL']).each do |org|
          n.orgpolicies.build
          if org.to_s.include?('{"lang"=>"')
            n.orgpolicies.last.url = ""
          else
            n.orgpolicies.last.url = org

          end

          n.orgpolicies.last.lang = q.pop
        end

        Array.wrap(x['info_URL']).each do |org|
          n.orginfos.build
          if org.to_s.include?('{"lang"=>"')
            n.orginfos.last.url = ""
          else

            n.orginfos.last.url = org
          end

          n.orginfos.last.lang = q.pop


        end
        n.save

        cur_institution_id = n.id


        if !Array.wrap(x['location']).nil?

          Array.wrap(x['location']).each do |item|
            loc = Location.new

            tmp_str = item['address']['street']
            loc.orig_import_string = tmp_str
            building_identifier = tmp_str.to_s.match(/[0-9]+(.*)/).to_s.match(/[A-z]/).to_s.upcase
            tmp_str = item['address']['street']

            clean_address = tmp_str.to_s.match(/[A-zÄÖÅäöå ]+[0-9]+/).to_s
            if clean_address == ""
              clean_address = item['address']['street']
            end

            loc.address = clean_address
            loc.identifier= building_identifier


            loc.city = item['address']['city']
            loc.country = item['address']['country']
            loc.longitude = item['longitude']
            loc.latitude = item['latitude']
            loc.institution_id = cur_institution_id
            loc.save

            while loc.save == false
              loc.identifier += "."
              loc.save
            end
            cur_location_id = loc.id
            Array.wrap(item['loc_name']).each do |lname|
              loc_name = LocName.new
              loc_name.location_id = cur_location_id
              loc_name.name = lname
              loc_name.lang = q.pop
              loc_name.save
            end

            enc_str = item['enc_level'].to_s
            if enc_str.include? "WPA2/AES"
              tmp_wpa2_aes = true
            else
              tmp_wpa2_aes = false
            end
            if enc_str.include? "WPA2/TKIP"
              tmp_wpa2_tkip = true
            else
              tmp_wpa2_tkip = false
            end
            if enc_str.include? "WPA/TKIP"
              tmp_wpa_tkip = true
            else
              tmp_wpa_tkip = false
            end
            if enc_str.include? "WPA/AES"
              tmp_wpa_aes = true
            else
              tmp_wpa_aes = false
            end


            res = Orgssid.where(institution_id: n.id,
                                name: item['SSID'],
                                port_restrict: item['port_restrict'],
                                transp_proxy: item['transp_proxy'],
                                ipv6: item['IPv6'],
                                nat: item['NAT'],
                                wpa_tkip: tmp_wpa_tkip,
                                wpa_aes: tmp_wpa_aes,
                                wpa2_tkip: tmp_wpa2_tkip,
                                wpa2_aes: tmp_wpa2_aes,
                                wired: item['wired'])
            if res.count == 1
              cur_ssid_id = res.first.id
            else
              orgssid = Orgssid.new
              orgssid.name = item['SSID']
              orgssid.port_restrict = value_bool(item['port_restrict'])
              orgssid.ipv6 = value_bool(item['IPv6'])
              orgssid.nat = value_bool(item['NAT'])
              orgssid.transp_proxy = value_bool(item['transp_proxy'])
              orgssid.wired = value_bool(item['wired'])
              orgssid.wpa2_aes = tmp_wpa2_aes
              orgssid.wpa2_tkip = tmp_wpa2_tkip
              orgssid.wpa_tkip = tmp_wpa_tkip
              orgssid.wpa_aes = tmp_wpa_aes
              orgssid.institution_id = cur_institution_id
              orgssid.save
              cur_ssid_id = orgssid.id
            end
            if !cur_location_id.nil?

              entry = Entry.new
              entry.location_id = cur_location_id
              entry.orgssid_id = cur_ssid_id
              entry.institution_id = cur_institution_id
              entry.ap_count = item['AP_no']
              entry.save
            end

          end

        end

      end
    end

  end


end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
    <% if @institution.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

          <ul>
            <% @institution.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>Country: <%= ENV['NRO_COUNTRY'] %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# set by NRO_COUNTRY environment variable for
      now</p>
    <div class="field">
      <%= f.label :institution_type %><br>
      <%= f.select :institution_type, @institution_types %>
    </div>
    <div class="field">
      <%= f.fields_for :orgnames do |oname| %>
          <%= oname.label :lang %>
              "<%= oname.text_field :lang, :readonly => true, class: "lang_field" %>"
              <%= :name %><br>
              <%= oname.text_field :name, class: "name_field" %><br>
      <% end %>

    </div>

    <div class="field">
      <%= f.label :inst_realm%><br>
      <%= f.text_field :inst_realm %>
      <p>csv if multiple e.g. realm1.tld,realm2.tld</p>
    </div>

    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>

    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <hr>
    <div class="field">
      <%= f.label :contact_name %><br>
      <%= f.text_field :contact_name %>
    </div>
    <div class="field">
      <%= f.label :contact_email %><br>
      <%= f.text_field :contact_email %>
    </div>
    <div class="field">
      <%= f.label :contact_phone %><br>
      <%= f.text_field :contact_phone %>
    </div>
    <div><p>Does not work with CSV values for now.</p>
    </div>
    <hr>
    <div class="field">
      <%= f.fields_for :orginfos do |oinf| %>
          <%= oinf.label :info %>
          "<%= oinf.text_field :lang, :readonly => true, class: "lang_field" %>"
          <%= :url %><br>
          <%= oinf.text_field :url %><br>
      <% end %>

    </div>

    <div class="field">

      <%= f.fields_for :orgpolicies do |policy| %>
          <%= policy.label :policy %>
          "<%= policy.text_field :lang, :readonly => true, class: "lang_field" %>"
          <%= :url %><br>
          <%= policy.text_field :url %><br>
      <% end %>

    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

    <div>

      <%= pp @institution.as_json %>
    </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Institution type</th>
      <th>Inst realm</th>
      <th>Address</th>
      <th>City</th>
      <th>Contact name</th>
      <th>Contact email</th>
      <th>Contact phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.primary_name %></td>
        <td><%= institution.institution_type %></td>
        <td><%= institution.inst_realm %></td>
        <td><%= institution.address %></td>
        <td><%= institution.city %></td>
        <td><%= institution.contact_name %></td>
        <td><%= institution.contact_email %></td>
        <td><%= institution.contact_phone %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/new_import.html.erb
<h1>Import XML-data</h1>
<%= form_tag 'institution/import', method: :post, remote: true, multipart: true, authenticity_token: true do %>
    <label for="file">Upload text File</label> <%= file_field_tag "file" %>
    <%= token_tag form_authenticity_token %>
    <%= submit_tag %>
<% end %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Institution</strong>
  <%= @institution.primary_name %>
</p>

<p>
  <strong>Country</strong>
  <%= @institution.country %>
</p>

<p>
  <strong>Institution type:</strong>
  <%= @institution.institution_type %>
</p>

<p>
  <strong>Inst realm:</strong>
  <%= @institution.inst_realm %>
</p>

<p>
  <strong>Address:</strong>
  <%= @institution.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @institution.city %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @institution.contact_name %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @institution.contact_email %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @institution.contact_phone %>
</p>

<p>
  <strong>Primary info url:</strong>
  <%= @institution.primary_info_url %>
</p>

<p>
  <strong>Primary policy url:</strong>
  <%= @institution.primary_policy_url %>
</p>


<p>
  <strong>APIKEY:</strong>
  <%= @institution.apikey %>
</p>
<hr>
<strong>Clicky API urls</strong>
<p><a href="/api/v1/<%=@institution.apikey%>/get/locations">Locations</a></p>
<p><a href="/api/v1/<%=@institution.apikey%>/get/ssids">SSIDs</a></p>
<p><a href="/api/v1/<%=@institution.apikey%>/get/policies">Policy URLs</a></p>
<p><a href="/api/v1/<%=@institution.apikey%>/get/infos">Info URLs</a></p>

<hr>
<table style="text-align: left;">
  <tr>
    <th>Address</th>
    <th>Identifier</th>
    <th>City</th>
    <th>AP Count</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Last updated</th>
    <th>Original import string</th>
  </tr><% @locations.each do |location| %>
      <tr><td><%= location.address %></td>
        <td><%= location.identifier %></td>
        <td><%= location.city %></td>
        <td><%= location.location_ap_count %></td>
        <td><%= location.longitude %></td>
        <td><%= location.latitude %></td>
        <td><%= location.updated_at %></td>
        <td><%= location.orig_import_string %></td>
      </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>